In [88]:
import pandas as pd

col_list = ["EVENT_DATE", "EVENT_TYPE","ADMIN1","ADMIN2","FATALITIES","SUB_EVENT_TYPE","ASSOC_ACTOR_1","ASSOC_ACTOR_2"]
df = pd.read_csv("USA_2020.csv", usecols=col_list)

#print(df)
#codes = pd.read_csv("FIPScodes")
state = df['ADMIN1']
df["ADMIN2"] = df['ADMIN2'].str.replace(" City", "")

event = {'Protests': 1,'Strategic developments': 5,'Violence against civilians': 10, 'Riots': 15, 'Battles': 5 }
df["EVENT_TYPE"] = [event[item] for item in df["EVENT_TYPE"]] 

#df["EVENT_TYPE"][vote2020["EVENT_TYPE"] == 'Protests'] = 1
#df["EVENT_TYPE"][vote2020["EVENT_TYPE"] == 'Strategic development'] = 5
#df["EVENT_TYPE"][vote2020["EVENT_TYPE"] == 'Violence against civilians'] = 10
#df["EVENT_TYPE"][vote2020["EVENT_TYPE"] == 'Riots'] = 15
#df["EVENT_TYPE"][vote2020["EVENT_TYPE"] == 'Battles'] = 5

num_unrest_per_county = df.groupby(['ADMIN1', 'ADMIN2'], as_index=False).agg({'EVENT_TYPE':['sum'],'EVENT_DATE': ['count'], 'FATALITIES':['sum']})
 

print(num_unrest_per_county)



       ADMIN1      ADMIN2 EVENT_TYPE EVENT_DATE FATALITIES
                                 sum      count        sum
0     Alabama     Baldwin          5          5          0
1     Alabama        Bibb          1          1          0
2     Alabama     Calhoun          5          5          0
3     Alabama    Cherokee          1          1          0
4     Alabama     Choctaw          1          1          0
...       ...         ...        ...        ...        ...
1596  Wyoming        Park          6          2          0
1597  Wyoming    Sheridan          1          1          0
1598  Wyoming    Sublette          1          1          0
1599  Wyoming  Sweetwater          1          1          0
1600  Wyoming       Teton          4          4          0

[1601 rows x 5 columns]


In [89]:
# reading voting data in 2020 per county per DEM and GOP

col_list6 = ["county_fips", "state_name", "county_name", "votes_dem", "votes_gop","total_votes" ]
vote2020 = pd.read_csv("2020.csv", usecols = col_list6)

binary_2020 = vote2020["votes_gop"]/vote2020["votes_dem"]

vote2020.insert(0, "binary_2020", value = binary_2020)

vote2020["binary_2020"][vote2020["binary_2020"] >= 1] = 1
vote2020["binary_2020"][vote2020["binary_2020"] < 1] = 0

vote2020 = vote2020.dropna()

vote2020["county_name"] = vote2020["county_name"].str.replace(" County", "")
print(vote2020)

      binary_2020 state_name  county_fips county_name  votes_gop  votes_dem  \
0             1.0    Alabama         1001     Autauga      19764       7450   
1             1.0    Alabama         1003     Baldwin      83055      24344   
2             1.0    Alabama         1005     Barbour       5605       4772   
3             1.0    Alabama         1007        Bibb       7508       1982   
4             1.0    Alabama         1009      Blount      24595       2627   
...           ...        ...          ...         ...        ...        ...   
3136          1.0    Wyoming        56037  Sweetwater      12197       3822   
3137          0.0    Wyoming        56039       Teton       4341       9848   
3138          1.0    Wyoming        56041       Uinta       7494       1591   
3139          1.0    Wyoming        56043    Washakie       3245        651   
3140          1.0    Wyoming        56045      Weston       3107        360   

      total_votes  
0           27639  
1          

/Users/niloofar/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/Users/niloofar/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()


In [61]:
# reading voting data in 2016 per county per DEM and GOP

col_list5 = ["combined_fips","state_name", "county_name", "votes_dem", "votes_gop","total_votes" ]
vote2016 = pd.read_csv("2016.csv", usecols = col_list5)

binary_2016 = vote2016["votes_gop"]/vote2016["votes_dem"]

vote2016.insert(0, "binary_2016", value = binary_2016)

vote2016["binary_2016"][vote2016["binary_2016"] >= 1] = 1
vote2016["binary_2016"][vote2016["binary_2016"] < 1] = 0

vote2016["county_name"] = vote2016["county_name"].str.replace(" County", "")

print(vote2016)

      binary_2016  votes_dem  votes_gop  total_votes county_name  \
0             1.0       5908      18110        24661     Autauga   
1             1.0      18409      72780        94090     Baldwin   
2             1.0       4848       5431        10390     Barbour   
3             1.0       1874       6733         8748        Bibb   
4             1.0       2150      22808        25384      Blount   
...           ...        ...        ...          ...         ...   
3136          1.0       3233      12153        16661  Sweetwater   
3137          0.0       7313       3920        12176       Teton   
3138          1.0       1202       6154         8053       Uinta   
3139          1.0        532       2911         3715    Washakie   
3140          1.0        294       2898         3334      Weston   

      combined_fips state_name  
0              1001    Alabama  
1              1003    Alabama  
2              1005    Alabama  
3              1007    Alabama  
4              100

/Users/niloofar/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/Users/niloofar/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()


In [90]:
vote_unrest = pd.merge(left = num_unrest_per_county, right = vote2016, how='inner', left_on=['ADMIN1','ADMIN2'], right_on=['state_name', 'county_name'])

vote_unrest = pd.merge(left = vote_unrest, right = vote2020, how = 'inner', left_on = ['combined_fips'], right_on = ['county_fips'])

print(vote_unrest)


     (ADMIN1, )  (ADMIN2, )  (EVENT_TYPE, sum)  (EVENT_DATE, count)  \
0       Alabama     Baldwin                  5                    5   
1       Alabama        Bibb                  1                    1   
2       Alabama     Calhoun                  5                    5   
3       Alabama    Cherokee                  1                    1   
4       Alabama     Choctaw                  1                    1   
...         ...         ...                ...                  ...   
1426    Wyoming        Park                  6                    2   
1427    Wyoming    Sheridan                  1                    1   
1428    Wyoming    Sublette                  1                    1   
1429    Wyoming  Sweetwater                  1                    1   
1430    Wyoming       Teton                  4                    4   

      (FATALITIES, sum)  binary_2016  votes_dem_x  votes_gop_x  total_votes_x  \
0                     0          1.0        18409        72780    

/Users/niloofar/opt/anaconda3/lib/python3.7/site-packages/pandas/core/reshape/merge.py:617: UserWarning: merging between different levels can give an unintended result (2 levels on the left, 1 on the right)
  warnings.warn(msg, UserWarning)


In [92]:
from sklearn.ensemble import RandomForestClassifier 
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import numpy as np
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import mean_squared_error

X = np.array(vote_unrest.iloc[:, [2, 3, 4]])
y = np.array(vote_unrest.iloc[:, 12])


kf = KFold(n_splits=5)
kf.get_n_splits(X)

score2 = []
for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    classifier = RandomForestClassifier(n_estimators=1000, random_state=0)
    classifier.fit(X_train, y_train) 
    y_pred2 = classifier.predict(X_test)
    score2.append(classifier.score(X_test, y_test))
    print(confusion_matrix(y_test, y_pred2))
    print(classification_report(y_test, y_pred2))
    print(accuracy_score(y_test, y_pred2))
    

    
print("average accuracy: ", sum(score2)/5)

[[ 53  51]
 [ 10 173]]
              precision    recall  f1-score   support

         0.0       0.84      0.51      0.63       104
         1.0       0.77      0.95      0.85       183

    accuracy                           0.79       287
   macro avg       0.81      0.73      0.74       287
weighted avg       0.80      0.79      0.77       287

0.7874564459930313
[[ 32  27]
 [  7 220]]
              precision    recall  f1-score   support

         0.0       0.82      0.54      0.65        59
         1.0       0.89      0.97      0.93       227

    accuracy                           0.88       286
   macro avg       0.86      0.76      0.79       286
weighted avg       0.88      0.88      0.87       286

0.8811188811188811
[[ 36  46]
 [ 10 194]]
              precision    recall  f1-score   support

         0.0       0.78      0.44      0.56        82
         1.0       0.81      0.95      0.87       204

    accuracy                           0.80       286
   macro avg       0.